# SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
#
# SPDX-License-Identifier: CC0-1.0

name: Slither Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crytic/slither-action@v0.4.0
        with:
          target: "."
          slither-args: "--include-paths ./src/contracts --skip-assembly"
          fail-on: "high"
